logging:
  level:
    org.apache.ibatis: TRACE  # 显示参数类型绑定细节
    com.baomidou.mybatisplus: DEBUG
    java.sql.PreparedStatement: DEBUG  # 显示JDBC层类型

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.224.195:3306/ismp?useSSL=false&useServerPrepStmts=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: xieguangqiang
  mail:
    host: smtp.qq.com
    port: 587
    username: 2864201368@qq.com
    password: onehhunksqknddfc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  data:
    redis:
      host: 47.113.224.195
      port: 6379
      password: qg@studio@2022
      timeout: 5000ms  # 连接超时和读写超时时间
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
        shutdown-timeout: 0ms  # 优雅关闭连接
      database: 2

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-field: is_deleted
      logic-delete-value: 1



